// SPDX-License-Identifier: APACHE-2.0
pragma solidity >=0.8.13;

import {IERC165} from "@openzeppelin/contracts/utils/introspection/IERC165.sol";

interface IGuess is IERC165 {
    // 284268bb
    // Error thrown when the message is not signed by the registered EVM signing key
    error Invalid_Enclave_Signature();
    // b97d0dcc
    // Error thrown when the attestation is not generated from an SGX enclave
    error SGX_Only();
    // 459fd41c
    // Error thrown when the attestation quote body does not contain a valid ISV report
    error Invalid_Quote_Body();
    // 6f7a8de0
    // Error thrown when the enclave mesaurement does not match the expected value
    error MRENCLAVE_Mismatch();
    // d5527477
    // Error thrown when the enclave signer does not match the expected value
    error MRSIGNER_Mismatch();
    // ad1477d5
    // Error thrown when the attestation report is not intended for this contract
    error Contract_Mismatch();

    // Event emiited when a new EVM signer is registed to the contract
    event SignerUpdated(address indexed signer);
    // Event emitted for a winning guess
    event RewardClaimed(address indexed winner, uint64 indexed round, uint64 guess);

    /**
     * @notice This method can only be called upon by the DCAP Portal contract
     * @notice to ensure a successful DCAP attestation has been performed
     * @notice extracts the EVM address of the enclave signer from the attestation report data
     */
    function attestAndSetSigner() external;

    /**
     * @notice The user calls this method to claim their reward for correctly guessing the winning number
     * @notice An NFT is minted to the user as a reward
     * @param round - the round number
     * @param winningNumber - the winning number for the given round
     * @param signature - the signature generated by the enclave
     */
    function claimReward(uint64 round, uint64 winningNumber, bytes calldata signature) external;
}
