// SPDX-License-Identifier: APACHE-2.0
pragma solidity ^0.8.13;

import { DcapLibCallback } from "@dcap-portal/src/lib/DcapLibCallback.sol";
import { Output } from "@dcap-portal/src/lib/Output.sol";

contract Guess is DcapLibCallback {

    bytes4 constant SGX_TEE = 0x00000000;
    uint256 constant ISV_ENCLAVE_REPORT_LENGTH = 384;

    // enclave configuration
    address public signer;
    bytes32 public immutable mrSigner;
    bytes32 public immutable mrEnclave;

    // 103b1887
    error Invalid_Enclave_Signer();
    // b97d0dcc
    error SGX_Only();
    // 459fd41c
    error Invalid_Quote_Body();
    // 6f7a8de0
    error MRENCLAVE_Mismatch();
    // d5527477
    error MRSIGNER_Mismatch();

    constructor (address _dcapPortal, bytes32 _mrsigner, bytes32 _mrEnclave) {
        __DcapLibCallbackInit(_dcapPortal);
        mrSigner = _mrsigner;
        mrEnclave = _mrEnclave;
    }

    /**
     * @notice submits the DCAP Attestation Quote to the Portal
     * @notice this method is then called by DCAP Portal after successful verification
     * @notice of the DCAP Attestation Report
     */
    function attestAndSetSigner() external fromDcapPortal {
        bytes memory attestationOutput = _attestationOutput();

        Output memory output = _deserializeAttestationOutput(attestationOutput);

        if (output.tee != SGX_TEE) {
            revert SGX_Only();
        }

        // With the Output object, you can do things like:
        // checking the TCB Status
        // see the advisory IDs based on the matching TCB level found in DCAP Verification
        // here we are checking the user report data because it contains the signer address
        // this signer address will then be stored in this contract
        // we are also making sure that the attestation is generated by a trusted enclave and enclave program
        // by checking MRSIGNER and MRENCLAVE values

        bytes32 mrSignerFound = _getMrSigner(output.quoteBody);
        if (mrSignerFound != mrSigner) {
            revert MRSIGNER_Mismatch();
        }

        bytes32 mrEnclaveFound = _getMrEnclave(output.quoteBody);
        if (mrEnclaveFound != mrEnclave) {
            revert MRENCLAVE_Mismatch();
        }

        // get the signer address
        bytes memory reportData = _attestationReportUserData(output.tee, output.quoteBody);
        (bytes32 lower, ) = _attestationReportUserDataBytes32(reportData);
        
        // the first 20 bytes of the report data contains the EVM address corresponds to the
        // private key generated in SGX
        signer = address(bytes20(lower));
    }

    function _getMrSigner(bytes memory _quoteBody) private pure returns (bytes32 mrsigner) {
        mrsigner = _extractWordFromQuoteBody(_quoteBody, 128);
    }

    function _getMrEnclave(bytes memory _quoteBody) private pure returns (bytes32 mrenclave) {
        mrenclave = _extractWordFromQuoteBody(_quoteBody, 64);
    }

    function _extractWordFromQuoteBody(bytes memory _quoteBody, uint256 _offset) private pure returns (bytes32 word) {
        if (_quoteBody.length != ISV_ENCLAVE_REPORT_LENGTH) {
            revert Invalid_Quote_Body();
        }

        assembly {
            let ptr := add(_quoteBody, 0x20)
            ptr := add(ptr, _offset)

            word := mload(ptr)
        }
    }

}
