// SPDX-License-Identifier: APACHE-2.0
pragma solidity ^0.8.13;

import {IERC165} from "@openzeppelin/contracts/utils/introspection/IERC165.sol";
import {ERC165} from "@openzeppelin/contracts/utils/introspection/ERC165.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

import {IGuess} from "./interfaces/IGuess.sol";

// Import the DcapLibCallback library from @dcap-portal/src/DcapLibCallback.sol
// Import the Attestation Output struct from @dcap-portal/src/lib/Output.sol

// The interface of the NFT is defined here so we don't have to import the entire contract
interface IGuessNFT {
    function safeMint(address to, uint256 tokenId) external;
}

// Once completed, remove abstract
abstract contract Guess is ERC165, IGuess {

    bytes4 constant SGX_TEE = 0x00000000;
    uint256 constant ISV_ENCLAVE_REPORT_LENGTH = 384;

    // NFT address
    IGuessNFT public immutable nft;

    // enclave configuration
    bytes32 public immutable mrSigner;
    bytes32 public immutable mrEnclave;

    // sharing storage slot #10
    address public signer;
    uint64 public nonce;

    // implement constructor to initialize the contract

    // Guard this function with the fromDcapPortal modifier
    // you may also use a stricter modifier, such as 
    //   fromDcapPortalAndOrigin: Requires a specific tx.origin
    //   fromDcapPortalAndSender: Requires a specific caller to DCAP Portal
    function attestAndSetSigner() external override {
        // Step 1: Extract the attestation output from the callback data with _attestationOutput()

        // The Output value is a serialized bytes array that consists of the following values:
        // [0-1]: quoteVersion (2 bytes)
        // [2-5]: tee (4 bytes)
        // [6]: tcbStatus (1 byte)
        // [7-12]: fmspcBytes (6 bytes)

        // Depending on the TEE type, the quote body may vary in length:
        // [13-396]: SGX ISV Report (384 bytes)
        // [13-596]: TDX ISV Report (584 bytes)

        // The TCB advisory IDs are stored in the remaining bytes as an abi-encoded string array

        // Step 2: Parse the attestation output with _deserializeAttestationOutput()
        // This gives us the Output in Solidity-friendly struct

        // Step 3: check whether the attestation were produced from an SGX enclave

        // Optional Steps: 
        // With the Output object, you can do things like:
        // checking the TCB Status
        // see the advisory IDs based on the matching TCB level found in DCAP Verification

        // Step 4: here we are making sure that the attestation is generated by a trusted enclave and enclave program
        // by checking MRSIGNER and MRENCLAVE values

        // Step 5: Once you have validated the MRENCLAVE and MRSIGNER values,
        // extract the attestation report from the Output with _attestationReportUserData()

        // Step 6: Extract the enclave signer address and the contract address from the report.
        // The report is 64-bytes, which the signer occupies 20-bytes of the first 32-bytes
        // whereas the contract address occupies the last 20-bytes of the report

        // The contract must make sure that the attestation report is intended for this contract
        // by comparing the contract address extracted from the report with the current contract address
        // Once a match is found, the signer address is safe to register in this contract.
    }

    function claimReward(uint64 round, uint64 winningNumber, bytes calldata signature) external override {
        // Step 1: Compute the digest
        // The message bytes are: (nonce || address(this) || round || winningNumber || msg.sender)
        // keccak256 is the hash function used to compute the digest

        // Step 2: Verify and recover the signer address from the signature
        // We must make sure that the recovered address matches with the registered signer address

        // Step 3: After validating the signature, we can now mint the NFT to the winner

        // Step 4: Increment the nonce to prevent replay attacks
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC165, IERC165) returns (bool) {
        return interfaceId == type(IGuess).interfaceId || super.supportsInterface(interfaceId);
    }

    function _getMrSigner(bytes memory _quoteBody) private pure returns (bytes32 mrsigner) {
        // TODO: use _extractWordFromQuoteBody to extract the MRSIGNER value from the quote body found in the attestation report
    }

    function _getMrEnclave(bytes memory _quoteBody) private pure returns (bytes32 mrenclave) {
        // TODO: use _extractWordFromQuoteBody to extract the MRENCLAVE value from the quote body found in the attestation report
    }

    // Extracts a 32-byte word from the quote body
    // This method only accepts a quote body containing SGX enclave report
    // that must be exactly 384 bytes in length
    // An SGX Enclave Report consists of the following values:
    // [0-15]: cpusvn (16 bytes)
    // [16-19]: miscselect (4 bytes)
    // [20-47]: reserved1 (28 bytes)
    // [48-63]: attributes (16 bytes)
    // [64-95]: mrenclave (32 bytes)
    // [96-127]: reserved2 (32 bytes)
    // [128-159]: mrsigner (32 bytes)
    // [160-255]: reserved3 (96 bytes)
    // [256-257]: isvprodid (2 bytes)
    // [258-259]: isvsvn (2 bytes)
    // [260-319]: reserved4 (60 bytes)
    // [320-383]: reportdata (64 bytes)
    function _extractWordFromQuoteBody(bytes memory _quoteBody, uint256 _offset) private pure returns (bytes32 word) {
        if (_quoteBody.length != ISV_ENCLAVE_REPORT_LENGTH) {
            revert Invalid_Quote_Body();
        }

        assembly {
            let ptr := add(_quoteBody, 0x20)
            ptr := add(ptr, _offset)

            word := mload(ptr)
        }
    }
}
